[pytest]
addopts = -v --alluredir=reports/allure-results
testpaths = tests
python_files = test_*.py
markers =
    smoke: Smoke tests
    regression: Regression tests
    login: Login related tests
    signup: Signup related tests
    e2e: End-to-end tests
